#!/bin/sh

### This method script wraps the import of a ZFS pool as an SMF service.
### Technically, it is an early version of phase1 "mount-main-pool" script,
### the difference is in the SMF service manifest that accompanies this one
### to define dependency on iSCSI initiator, so startup/shutdown are better
### ordered with regard to networking.
### Copyright (C) 2010-2017 by Jim Klimov, on the terms of CDDL license

DELAY=600

case "$1" in
	start)
		if [ -f /etc/zfs/delay.dcpool ]; then
			D="`head -1 /etc/zfs/delay.dcpool`"
			[ "$D" -gt 0 ] 2>/dev/null && DELAY="$D"
			echo "`date`: Delay requested... ${DELAY}sec"
			sleep ${DELAY}
			echo "`date`: Done sleeping"
		fi

		if [ -f /etc/zfs/noimport-dcpool ]; then
			echo "`date`: /etc/zfs/noimport-dcpool block-file reappeared. Aborting."
			exit 0
		fi

		[ -d /dcpool/export -o -f /etc/zfs/noimport-dcpool ] || \
			( echo "`date`: beginning dcpool import..."
			  time zpool import -o cachefile=none dcpool
			  RET=$?
			  echo "`date`: dcpool import complete ($RET)"
			  exit $RET )
		;;
	stop)
		[ ! -d /dcpool/export ] || \
			time zpool export dcpool || \
			while ! time zpool export -f dcpool; do sleep 1; done
		;;
esac

